[build-system]
requires = ["setuptools>62.6.0", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.ruff]
select = ["E", "F", "I"]

[tool.setuptools_scm]
write_to = "is3g/_version.py"
