name: Upload to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: python -m pip install --user build
      - name: Build Python package
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish Python package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
